services:
  survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    expose:
      - "25565"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "TUINITY"
      ONLINE_MODE: "FALSE"
      FORCE_GAMEMODE: "true"
      MODE: "survival"
    restart: unless-stopped
    networks:
      - mc

  creative:
    container_name: minecraft-creative
    image: itzg/minecraft-server
    expose:
      - "25565"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_creative
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "TUINITY"
      ONLINE_MODE: "FALSE"
    restart: unless-stopped
    networks:
      - mc

  events:
    container_name: minecraft-events
    image: itzg/minecraft-server
    expose:
      - "25565"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_events
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "TUINITY"
      ONLINE_MODE: "FALSE"
    restart: unless-stopped
    networks:
      - mc

  bedwars:
    container_name: minecraft-bedwars
    image: itzg/minecraft-server
    expose:
      - "25565"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_bedwars
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.9.4"
      ONLINE_MODE: "FALSE"
    restart: unless-stopped
    networks:
      - mc

  proxy:
    container_name: minecraft-proxy
    image: itzg/bungeecord
    ports:
      - "25565:25565"
    volumes:
      - "/home/newtonadmin/waterfall/:/config"
      - "/home/newtonadmin/waterfall/plugins:/plugins"
    restart: unless-stopped
    environment:
      TYPE: "WATERFALL"
    networks:
      - mc


# Allows Internal Communication Between Minecraft Containers
networks:
  mc:
    driver: bridge