services:


  survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    expose:
      - "25565"
    ports:
      - "8100:8100"
      - "9225:9225"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_survival
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "TUINITY"
      ONLINE_MODE: "FALSE"
      FORCE_GAMEMODE: "true"
      MODE: "survival"
      MAX_MEMORY: "1G"
      TZ: "America/Phoenix"
      ENABLE_AUTOPAUSE: "FALSE"
    restart: unless-stopped
    networks:
      - mc
    deploy:
        resources:
          reservations:
              cpus: 0.25
              memory: 128M



  forge:
    container_name: minecraft-forge
    image: itzg/minecraft-server:java8
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_forge
        target: /data
    expose:
      - "25565"
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE"
      MAX_MEMORY: "1G"
      TZ: "America/Phoenix"
      TYPE: "FORGE"
      ENABLE_AUTOPAUSE: "TRUE"
      VERSION: "1.12.2"
    restart: unless-stopped
    networks:
      - mc
    deploy:
        resources:
          reservations:
              cpus: 0.25
              memory: 128M

  proxy:
    container_name: minecraft-proxy
    image: itzg/bungeecord
    ports:
      - "25565:25577"
      - "8804:8804"
      - "19132:19132/udp"
    volumes:
      - "/home/newtonadmin/minecraft_proxy/:/config"
      - "/home/newtonadmin/minecraft_proxy/plugins:/server/plugins"
      - "/home/newtonadmin/minecraft_proxy/:/server"
    restart: unless-stopped
    environment:
      TYPE: "WATERFALL"
      TZ: "America/Phoenix"

    networks:
      - mc
    deploy:
        resources:
          limits:
              cpus: 0.50
              memory: 218M



# Allows Internal Communication Between Minecraft Containers
networks:
  mc:
    driver: bridge
