services:
  survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    expose:
      - "25565"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_survival
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ONLINE_MODE: "FALSE"
      FORCE_GAMEMODE: "true"
      MODE: "survival"
      MAX_MEMORY: "1G"
    restart: unless-stopped
    networks:
      - mc
    deploy:
        resources:
          reservations:
              cpus: 0.25
              memory: 128M
  events:
    container_name: minecraft-events
    image: itzg/minecraft-server
    expose:
      - "25565"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_events
        target: /data
    restart: unless-stopped
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      MAX_MEMORY: "1G"
    networks:
      - mc
    deploy:
        resources:
          reservations:
              cpus: 0.25
              memory: 128M
     

  proxy:
    container_name: minecraft-proxy
    image: itzg/bungeecord
    ports:
      - "25565:25577"
    volumes:
      - "/home/newtonadmin/minecraft_proxy/:/config"
      - "/home/newtonadmin/minecraft_proxy/plugins:/plugins"
    restart: unless-stopped
    environment:
      TYPE: "WATERFALL"

    networks:
      - mc
    deploy:
        resources:
          limits:
              cpus: 0.50
              memory: 218M



# Allows Internal Communication Between Minecraft Containers
networks:
  mc:
    driver: bridge
