services:

  database:
    container_name: minecraft-database
    image: mariadb
    restart: unless-stopped
    environment: 
      MYSQL_ROOT_PASSWORD: "N3wt!3MARIADB"
    expose:
      - "3306"
    volumes:
      - "/home/newtonadmin/minecraft_database/:/etc/mysql/"
    deploy:
      resources:
        limits:
            cpus: 0.50
            memory: 128M
    networks:
      - mc

  adminer:
    image: adminer
    container_name: minecraft-adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - mc


  survival:
    container_name: minecraft-survival
    image: itzg/minecraft-server
    expose:
      - "25565"
    ports:
      - "8100:8100"
      - "9225:9225"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft_survival
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "TUINITY"
      ONLINE_MODE: "FALSE"
      FORCE_GAMEMODE: "true"
      MODE: "survival"
      MAX_MEMORY: "1G"
      TZ: "America/Phoenix"
      ENABLE_AUTOPAUSE: "FALSE"
    restart: unless-stopped
    networks:
      - mc
    deploy:
        resources:
          reservations:
              cpus: 0.25
              memory: 128M





  proxy:
    container_name: minecraft-proxy
    image: itzg/bungeecord
    ports:
      - "25565:25577"
      - "8804:8804"
      - "19132:19132/udp"
    volumes:
      - "/home/newtonadmin/minecraft_proxy/:/server"
    restart: unless-stopped
    environment:
      TYPE: "WATERFALL"
      TZ: "America/Phoenix"

    networks:
      - mc
    deploy:
        resources:
          limits:
              cpus: 0.50
              memory: 512M



# Allows Internal Communication Between Minecraft Containers
networks:
  mc:
    driver: bridge
