services:
  survival:
    image: itzg/minecraft-server
    expose:
      - "25565"
    volumes:
      - type: bind
        source: /home/newtonadmin/minecraft
        target: /data
    environment:
      EULA: "TRUE"
      TYPE: "TUINITY"
      ONLINE_MODE: "false"
      FORCE_GAMEMODE: "true"
      MODE: "survival"
      MOTD: "Survival Minecraft Server"
    restart: unless-stopped
    networks:
      - mc

  mcb-bungee:
    container_name: mcb-bungee
    image: itzg/bungeecord
    ports:
      - "25565:25565"
    volumes:
      - "/home/newtonadmin/waterfall/:/config"
    restart: unless-stopped
    environment:
      TYPE: "WATERFALL"
    networks:
      - mc


# Allows Internal Communication Between Minecraft Containers
networks:
  mc:
    driver: bridge