  database:
    container_name: minecraft-database
    image: mariadb
    restart: unless-stopped
    expose:
      - "3306"
    volumes:
      - "/home/newtonadmin/minecraft_database/:/etc/mysql/"
    deploy:
        resources:
          limits:
              cpus: 0.50
              memory: 218M
    networks:
      - mc

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - mc